# Generated by Django 4.2.8 on 2023-12-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='about',
            field=models.TextField(blank=True),
        ),
    ]
