# Generated by Django 4.2.8 on 2023-12-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_about_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
