# Generated by Django 4.2.8 on 2023-12-27 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_about_master'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='master',
            new_name='degree',
        ),
    ]
