# Generated by Django 4.2.8 on 2023-12-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_rename_master_about_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryservice',
            name='description',
            field=models.TextField(blank=True, max_length=100000, null=True),
        ),
    ]
