# Generated by Django 4.2.8 on 2023-12-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_categoryservice_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
