# Generated by Django 4.2.8 on 2023-12-27 19:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settings', '0007_resume_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resume',
            new_name='Education',
        ),
    ]
