# Generated by Django 4.2.8 on 2023-12-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='description',
            field=models.TextField(blank=True, max_length=100000, null=True),
        ),
    ]
