# Generated by Django 4.2.8 on 2023-12-27 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0012_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='githup_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='linkedin_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
