# Generated by Django 4.2.8 on 2023-12-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0013_info_githup_link_info_linkedin_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
